option knitro_options "algorithm=1 ms_enable=1 ms_maxsolves=50 ms_terminate=1 ms_savetol=0.01 feastol=1e-5 opttol=1e-5 bar_initpt=3 bar_murule=6 bar_penaltyrule=2 linsolver=0 scale=3 honorbnds=1 outlev=3 maxtime_real=1200 numthreads=4 presolve=1 bar_refinement=1 debug=0";




printf "---------------------------- Solution header data ----------------------------\n";
solve;

printf "---------------------------- Container and geometric considerations  ----------------------------\n";
printf "Container type: %s\n", container_type;
printf "Structural conservation type: %s\n", geometric_conservation;

# Status info

printf "---------------------------- Solution execution data ----------------------------\n";
display solve_result_num, solve_result;

# Data variables
printf "---------------------------- Solution data ----------------------------\n";
display card(figures), coords, radius, softness;

printf "---------------------------- Solution coords data ----------------------------\n";
display distances;
   
# Time stats
printf "---------------------------- Solution stats data ----------------------------\n";
display _ampl_time, _total_solve_time, _ampl_elapsed_time, _ampl_user_time;   

printf "Total time elapsed: $%6.2f.\n", _total_solve_time;
display _total_solve_time;

printf "---------------------------- Solution miscs data ----------------------------\n";
display tetrahedron_volume;

printf "---------------------------- Solution miscs data ----------------------------\n";
display tetrahedron_surface_area;

quit;

